services:
  - docker:stable-dind

stages:
  - integration
  - delivery
  - deployment

.common_packages:
  before_script:
    - apk add --no-cache bash git

.common_deps:
  cache:
    key: ${CACHE_DIR}-${CI_COMMIT_REF_SLUG}
    paths: ["${CACHE_DIR}"]
  artifacts:
    paths: ["${BUILD_DIR}"]
  before_script:
    - mkdir -m 777 -p ${CACHE_DIR} ${BUILD_DIR}

CI_amd64:
  stage: integration
  variables:
    ARCH: amd64
    CACHE_DIR: .ci_cache_${ARCH}
    BUILD_DIR: .ci_out_${ARCH}
  image: ${ARCH}/docker:latest
  extends: [".common_packages", ".common_deps"]
  only: ["branches"]
  script:
    - ./ci/build.sh
    - ./ci/test.sh
    - ./ci/coverage.sh

CI_arm64v8:
  stage: integration
  variables:
    ARCH: arm64v8
    CACHE_DIR: .ci_cache_${ARCH}
    BUILD_DIR: .ci_out_${ARCH}
  image: ${ARCH}/docker:latest
  extends: [".common_packages", ".common_deps"]
  only: ["branches"]
  script:
    - ./ci/build.sh
    - ./ci/test.sh

# CD:
#   stage: delivery
#   image: docker:latest
#   extends: [".common_packages"]
#   only: ["master"]
#   needs: ["CI_amd64","CI_arm64v8"]
#   script:
#     - ./ci/deliver.sh
