dist: xenial
language: minimal
os: linux
sudo: true

env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

cache:
  directories:
    - "$TRAVIS_BUILD_DIR/build/"

jobs:
  include:
    - stage: "Build"
      script:
        - sudo apt-get -qq -y update
        - sudo apt-get -qq -y install g++-6 make cmake libssl-dev libcurl4-openssl-dev
        - make -e release
    - stage: "Test"
      script:
        - sudo apt-get -qq -y update
        - sudo apt-get -qq -y install libssl libcurl4-openssl
        - ./run.sh release test
