dist: xenial
language: shell
os: linux
services: docker

cache:
  directories:
  - .custom_cache

if: tag IS blank

jobs:
  include:
    - stage: "Test"
      if: branch != master
      install: skip
      script:
        - ./ci/build.sh
        - ./ci/test.sh
        - ./ci/coverage.sh
        - sudo chown -R ${USER} .custom_cache
    - stage: "Deliver"
      if: branch = master
      install: skip
      script:
        - ./ci/build.sh
        - ./ci/test.sh
        - ./ci/deliver.sh
        - ./ci/coverage.sh
        - sudo chown -R ${USER} .custom_cache
