language: cpp
compiler: gcc
os: linux
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++-6
      - make
      - cmake
      - libssl-dev
      - libcurl4-openssl-dev

jobs:
  include:
    - stage: "Build"
      script:
        - export CXX="g++-6"
        - make -e debug
    - stage: "Test"
      script:
        - ./run.sh debug test
