dist: xenial
language: minimal
os: linux
sudo: false
services: docker
git.clone: false
install: skip
script:
  - docker pull debian:stretch-slim
  - docker run --mount type=bind,source="$(pwd)/ci",target=/ci debian:stretch-slim /bin/bash -c 'cd /ci; /ci/test.sh'
