dist: xenial
language: minimal
os: linux
sudo: true

env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

cache:
  directories:
    - "$TRAVIS_BUILD_DIR/build/"

jobs:
  include:
    - stage: "Build"
      script:
        - sudo apt-get -q update
        - sudo apt-get -q -y install g++-6 make cmake libssl-dev libcurl4-openssl-dev
        - make -e debug
    - stage: "Test"
      script:
        - sudo apt-get -q update
        - sudo apt-get -q -y install libssl1.0.0 libcurl3
        - ./run.sh debug test
