dist: xenial
language: minimal
os: linux

env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

cache:
  directories:
    - "$TRAVIS_BUILD_DIR/build/"

jobs:
  include:
    - stage: "Build"
      script:
        - apt-get -qq -y update
        - apt-get -qq -y install g++-6 make cmake libssl-dev libcurl4-openssl-dev
        - make -e debug
    - stage: "Test"
      script:
        - apt-get -qq -y update
        - apt-get -qq -y install libssl libcurl4-openssl
        - ./run.sh debug test
