language: cpp
compiler: gcc
os: linux
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++-6
      - make
      - cmake
      - libssl-dev
      - libcurl4-openssl-dev
env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

jobs:
  include:
    - stage: "Build"
      script:
        - make -e debug
    - stage: "Test"
      script:
        - ./run.sh debug test
