language: cpp
compiler: gcc
os: linux
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - make
      - cmake
      - libssl-dev
      - libcurl4-openssl-dev
env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

cache:
  directories:
    - "$TRAVIS_BUILD_DIR/build/"

jobs:
  include:
    - stage: "Build"
      script:
        - make -e debug
    - stage: "Test"
      script:
        - ./run.sh debug test
