dist: xenial
language: minimal
os: linux
sudo: false
services: docker
git:
  depth: false

jobs:
  include:
    - stage: "Test"
      if: branch != master
      install: skip
      script:
        - docker pull debian:stretch-slim
        - docker run --mount type=bind,source="$(pwd)",target=/repository debian:stretch-slim /bin/bash -c 'cd /repository; ./ci/build.sh'
        - docker run --mount type=bind,source="$(pwd)",target=/repository debian:stretch-slim /bin/bash -c 'cd /repository; ./ci/test.sh'
    - stage: "Deliver"
      if: branch = master
      install: skip
      script:
        # vars
        - export PROJECT_NAME=$(./ci/get_project_name.sh)
        - export PROJECT_VERSION=$(./ci/get_project_version.sh)
        - export RELEASE_TAG="${PROJECT_NAME}-${PROJECT_VERSION}"
        # grant docker login
        - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
        # push new tag, locking version and grant git write access
        - git config user.name "${GIT_USERNAME}"
        - git config user.email "${GIT_USEREMAIL}"
        - git remote set-url origin "https://${GIT_USERNAME}:${GIT_PASSWORD}@${GIT_REPOSITORY_URL}"
        - git fetch --tag
        - git tag ${RELEASE_TAG} && git push origin tag ${RELEASE_TAG}
        # build docker image
        - docker pull debian:stretch-slim
        - docker run --mount type=bind,source="$(pwd)",target=/repository debian:stretch-slim /bin/bash -c 'cd /repository; ./ci/build.sh'
        - docker run --mount type=bind,source="$(pwd)",target=/repository debian:stretch-slim /bin/bash -c 'cd /repository; ./ci/test.sh'
        - docker build -t "${DOCKER_REPOSITORY}:${RELEASE_TAG}" -f ci/docker/Dockerfile .
        # push image tags
        - docker push "${DOCKER_REPOSITORY}:${RELEASE_TAG}"
        - docker tag "${DOCKER_REPOSITORY}:${RELEASE_TAG}" "${DOCKER_REPOSITORY}:${PROJECT_NAME}-latest"
        - docker push "${DOCKER_REPOSITORY}:${PROJECT_NAME}-latest"
        # if error, remove remote new tag, free version
